### ISSUE TITLE
Remove npm packages from the repo

### ISSUE THREAD

**Issue by johngully** [patternpack/patternpack.github.io#2]
It appears that susy has been committed to the repo.  We should not be committing dependencies to the repository.

**Comment by marcelosomers** [comment]
Fixed by commits https://github.com/patternpack/patternpack.github.io/commit/ff91d834efb877f50a2b0bf8b6734e66405db96d and https://github.com/patternpack/patternpack.github.io/commit/adb6905a358386781590e464869f5516db7ae4f8
